### PR TITLE
Update Notifications stories

### PR DESCRIPTION
**Pull request by bayasdev**
## What does this do

This PR updates the Notifications StoryBook stories to incorporate an interactive demo of the component.

Screenshot 2024-10-09 at 12 12 47 PM
Screenshot 2024-10-09 at 12 13 12 PM
Screenshot 2024-10-09 at 12 21 31 PM
Screenshot 2024-10-09 at 12 13 21 PM
Screenshot 2024-10-09 at 12 13 31 PM
Screenshot 2024-10-09 at 12 13 43 PM
Screenshot 2024-10-09 at 12 13 56 PM
Screenshot 2024-10-09 at 12 14 24 PM
Screenshot 2024-10-09 at 12 16 01 PM

### CODE REVIEW

**Comment by bayasdev** [comment]
@sen-io @oscarocastellanos please take a look ;)

**Review by bexsoft — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]
looking good, I'll let design team review on the design and style. 
And @bexsoft  on the code :D

**Review by oscarocastellanos — APPROVED** [review]
This looks great! We are thinking of just using top center and bottom right always, but we can leave the rest just to have the options available.

**Comment by sen-io** [comment]
@bayasdev Looking good!  Just a few things.... there should be two kinds of notifications, either a single line or a card.  The single line ones are a little different  than just the cards with not body text.  See how they do not use bold text and the alignment with the icon is a little different than the card.
Screenshot 2024-10-09 at 10 37 15 AM

also, the single line notice has the action inline (if included)
Screenshot 2024-10-09 at 10 39 08 AM

**VS** 
The card appearance uses the bold title and alignment is a little different with the icon
Screenshot 2024-10-09 at 10 40 06 AM

which is consistent with the design alignment
Screenshot 2024-10-09 at 10 40 45 AM


### Lastly
These elements are supposed to have slight shadows.

**Comment by bayasdev** [comment]
> @bayasdev Looking good!  Just a few things.... there should be two kinds of notifications, either a single line or a card.  The single line ones are a little different  than just the cards with not body text.  See how they do not use bold text and the alignment with the icon is a little different than the card.
> 
> Screenshot 2024-10-09 at 10 37 15 AM
> 
> 
> 
> also, the single line notice has the action inline (if included)
> 
> Screenshot 2024-10-09 at 10 39 08 AM
> 
> 
> 
> **VS** 
> 
> The card appearance uses the bold title and alignment is a little different with the icon
> 
> Screenshot 2024-10-09 at 10 40 06 AM
> 
> 
> 
> which is consistent with the design alignment
> 
> Screenshot 2024-10-09 at 10 40 45 AM
> 
> 
> 
> 
> 
> ### Lastly
> 
> These elements are supposed to have slight shadows.
> 
> 

Yes, all of these designs can be achieved through the options object and React composition. You can even change the inner CSS of the rendered card to match the requirement.

Please note that a max width of 600px per card was set in the animated card container to prevent overflows.

**Comment by bayasdev** [comment]
@sen-io if the card design does not match the requirements then it should be addressed with a PR for NotificationAlert component

**Comment by bayasdev** [comment]
> @sen-io if the card design does not match the requirements then it should be addressed with a PR for NotificationAlert component. Same for Button and so on.

**Comment by bayasdev** [comment]
> @sen-io if the card design does not match the requirements then it should be addressed with a PR for NotificationAlert component. Same goes for Button and so on.

This is just a wrapper for rendering and compositing the components on the screen :D

**Comment by sen-io** [comment]
@bayasdev Thank you for clarifying on those points!

**Pull request merged**
